apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmanager-deployment
  labels:
    app: taskmanager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taskmanager
  template:
    metadata:
      labels:
        app: taskmanager
    spec:
      containers:
      - name: taskmanager-container
        image: sohelqt8797/taskmanager:latest

        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production
